using System;
using System.Collections.Generic;

namespace ClipboardTranslator
{
    public static class LanguageSupport
    {
        public static List<Tuple<string, string>> LanguageList = new List<Tuple<string, string>>
        {
            Tuple.Create("Afrikaans","af"),
            Tuple.Create("Albanian","sq"),
            Tuple.Create("Amharic","am"),
            Tuple.Create("Arabic","ar"),
            Tuple.Create("Armenian","hy"),
            Tuple.Create("Azeerbaijani","az"),
            Tuple.Create("Basque","eu"),
            Tuple.Create("Belarusian","be"),
            Tuple.Create("Bengali","bn"),
            Tuple.Create("Bosnian","bs"),
            Tuple.Create("Bulgarian","bg"),
            Tuple.Create("Catalan","ca"),
            Tuple.Create("Cebuano","ceb"),
            Tuple.Create("Chinese (Simplified)","zh-CN"),
            Tuple.Create("Chinese (Traditional)","zh-TW"),
            Tuple.Create("Corsican","co"),
            Tuple.Create("Croatian","hr"),
            Tuple.Create("Czech","cs"),
            Tuple.Create("Danish","da"),
            Tuple.Create("Dutch","nl"),
            Tuple.Create("English","en"),
            Tuple.Create("Esperanto","eo"),
            Tuple.Create("Estonian","et"),
            Tuple.Create("Finnish","fi"),
            Tuple.Create("French","fr"),
            Tuple.Create("Frisian","fy"),
            Tuple.Create("Galician","gl"),
            Tuple.Create("Georgian","ka"),
            Tuple.Create("German","de"),
            Tuple.Create("Greek","el"),
            Tuple.Create("Gujarati","gu"),
            Tuple.Create("Haitian Creole","ht"),
            Tuple.Create("Hausa","ha"),
            Tuple.Create("Hawaiian","haw"),
            Tuple.Create("Hebrew","iw"),
            Tuple.Create("Hindi","hi"),
            Tuple.Create("Hmong","hmn (ISO-639-2)"),
            Tuple.Create("Hungarian","hu"),
            Tuple.Create("Icelandic","is"),
            Tuple.Create("Igbo","ig"),
            Tuple.Create("Indonesian","id"),
            Tuple.Create("Irish","ga"),
            Tuple.Create("Italian","it"),
            Tuple.Create("Japanese","ja"),
            Tuple.Create("Javanese","jw"),
            Tuple.Create("Kannada","kn"),
            Tuple.Create("Kazakh","kk"),
            Tuple.Create("Khmer","km"),
            Tuple.Create("Korean","ko"),
            Tuple.Create("Kurdish","ku"),
            Tuple.Create("Kyrgyz","ky"),
            Tuple.Create("Lao","lo"),
            Tuple.Create("Latin","la"),
            Tuple.Create("Latvian","lv"),
            Tuple.Create("Lithuanian","lt"),
            Tuple.Create("Luxembourgish","lb"),
            Tuple.Create("Macedonian","mk"),
            Tuple.Create("Malagasy","mg"),
            Tuple.Create("Malay","ms"),
            Tuple.Create("Malayalam","ml"),
            Tuple.Create("Maltese","mt"),
            Tuple.Create("Maori","mi"),
            Tuple.Create("Marathi","mr"),
            Tuple.Create("Mongolian","mn"),
            Tuple.Create("Myanmar (Burmese)","my"),
            Tuple.Create("Nepali","ne"),
            Tuple.Create("Norwegian","no"),
            Tuple.Create("Nyanja (Chichewa)","ny"),
            Tuple.Create("Pashto","ps"),
            Tuple.Create("Persian","fa"),
            Tuple.Create("Polish","pl"),
            Tuple.Create("Portuguese (Portugal , Brazil)","pt"),
            Tuple.Create("Punjabi","pa"),
            Tuple.Create("Romanian","ro"),
            Tuple.Create("Russian","ru"),
            Tuple.Create("Samoan","sm"),
            Tuple.Create("Scots Gaelic","gd"),
            Tuple.Create("Serbian","sr"),
            Tuple.Create("Sesotho","st"),
            Tuple.Create("Shona","sn"),
            Tuple.Create("Sindhi","sd"),
            Tuple.Create("Sinhala (Sinhalese)","si"),
            Tuple.Create("Slovak","sk"),
            Tuple.Create("Slovenian","sl"),
            Tuple.Create("Somali","so"),
            Tuple.Create("Spanish","es"),
            Tuple.Create("Sundanese","su"),
            Tuple.Create("Swahili","sw"),
            Tuple.Create("Swedish","sv"),
            Tuple.Create("Tagalog (Filipino)","tl"),
            Tuple.Create("Tajik","tg"),
            Tuple.Create("Tamil","ta"),
            Tuple.Create("Telugu","te"),
            Tuple.Create("Thai","th"),
            Tuple.Create("Turkish","tr"),
            Tuple.Create("Ukrainian","uk"),
            Tuple.Create("Urdu","ur"),
            Tuple.Create("Uzbek","uz"),
            Tuple.Create("Vietnamese","vi"),
            Tuple.Create("Welsh","cy"),
            Tuple.Create("Xhosa","xh"),
            Tuple.Create("Yiddish","yi"),
            Tuple.Create("Yoruba","yo"),
            Tuple.Create("Zulu","zu"),
        };
    }
}
